# .github/workflows/copy_to_s3.yml
name: Deploy to AWS S3
on:
  workflow_call:
    inputs:
      aws_key:
        required: true
        type: string
      aws_secret_key:
        required: true
        type: string
      s3_bucket_name:
        required: true
        type: string
      aws_region:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_key }}
        aws-secret-access-key: ${{ inputs.aws_secret_key }}
        aws-region: ${{ inputs.aws_region }}
    - name: set node version to 16.17.0
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.0
    - name: npm Install
      run: |
        npm i
    - name: Deploy to S3
      run: |
        aws s3 . public/ s3://${{ inputs.s3_bucket_name  }} --recursive --quiet
